package com.app.entity;

import java.util.Date;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.birthday
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.status
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.birthday
	 * @return  the value of users.birthday
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.birthday
	 * @param birthday  the value for users.birthday
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.status
	 * @return  the value of users.status
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.status
	 * @param status  the value for users.status
	 * @mbg.generated  Thu Mar 03 15:35:11 ICT 2022
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}