package demo.dc.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import demo.dc.app.model.WorksSortingAndPagingRequest;
import demo.dc.domain.entity.Works;
import demo.dc.domain.entity.WorksExample;

@Component
@Mapper
public interface WorksMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	long countByExample(WorksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int deleteByExample(WorksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int insert(Works record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int insertSelective(Works record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	List<Works> selectByExample(WorksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	Works selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Works record, @Param("example") WorksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int updateByExample(@Param("record") Works record, @Param("example") WorksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int updateByPrimaryKeySelective(Works record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	int updateByPrimaryKey(Works record);
	
	/**
	 * Get work sort from small to large and sort from big to small
	 */
	List<Works> selectBySorting(WorksSortingAndPagingRequest worksSorting);
}