package demo.dc.domain.entity;

import java.util.Date;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public class Works {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column works.id
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column works.work_name
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	private String workName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column works.starting_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	private Date startingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column works.ending_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	private Date endingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column works.status
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column works.id
	 * @return  the value of works.id
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column works.id
	 * @param id  the value for works.id
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column works.work_name
	 * @return  the value of works.work_name
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public String getWorkName() {
		return workName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column works.work_name
	 * @param workName  the value for works.work_name
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public void setWorkName(String workName) {
		this.workName = workName == null ? null : workName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column works.starting_date
	 * @return  the value of works.starting_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public Date getStartingDate() {
		return startingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column works.starting_date
	 * @param startingDate  the value for works.starting_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public void setStartingDate(Date startingDate) {
		this.startingDate = startingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column works.ending_date
	 * @return  the value of works.ending_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public Date getEndingDate() {
		return endingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column works.ending_date
	 * @param endingDate  the value for works.ending_date
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public void setEndingDate(Date endingDate) {
		this.endingDate = endingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column works.status
	 * @return  the value of works.status
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column works.status
	 * @param status  the value for works.status
	 * @mbg.generated  Fri Mar 04 16:26:54 ICT 2022
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}